apiVersion: v1
kind: Service
metadata:
  name: {{ include "pintu-chart.fullname" . }}-svc
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Chart.Name }}