trivia:
  pullPolicy: "IfNotPresent"
  replica: 1
  env:
    FRONTEND_PORT: "8080"
    BACKEND_PORT: "3000"
  backend:
    image: "move4up/trivia-backend"
    tag: "1.0.0"
  frontend:
    image: "move4up/trivia-frontend"
    tag: "1.0.0"
service:
  type: LoadBalancer
  port: 8080
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
  # targetMemoryUtilizationPercentage: 80